# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/doro/hero/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/doro/hero/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/doro/hero/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/doro/hero/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/doro/hero/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/doro/hero/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/doro/hero/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/doro/hero/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/doro/hero/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/doro/hero/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/doro/hero/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/doro/hero/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/doro/hero/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/doro/hero/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/doro/hero/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/doro/hero/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/doro/hero/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/doro/hero/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/doro/hero/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/doro/hero/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/doro/hero/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/doro/hero/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/doro/hero/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/doro/hero/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/doro/hero/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/doro/hero/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_mtp.xml:system/etc/mixer_paths_mtp.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skuh.xml:system/etc/mixer_paths_qrd_skuh.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skuhf.xml:system/etc/mixer_paths_qrd_skuhf.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skui.xml:system/etc/mixer_paths_qrd_skui.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_skuk.xml:system/etc/mixer_paths_skuk.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_wcd9306.xml:system/etc/mixer_paths_wcd9306.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_wcd9330.xml:system/etc/mixer_paths_wcd9330.xml \
    vendor/doro/hero/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/doro/hero/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/doro/hero/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/doro/hero/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/doro/hero/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/doro/hero/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/doro/hero/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/doro/hero/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/doro/hero/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/doro/hero/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
    vendor/doro/hero/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
    vendor/doro/hero/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    vendor/doro/hero/proprietary/vendor/bin/slim_ap_daemon:system/vendor/bin/slim_ap_daemon \
    vendor/doro/hero/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/doro/hero/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/doro/hero/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/doro/hero/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/doro/hero/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/doro/hero/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/doro/hero/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/doro/hero/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/doro/hero/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/doro/hero/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/doro/hero/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/doro/hero/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/doro/hero/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/doro/hero/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/doro/hero/proprietary/vendor/etc/msm_irqbalance.conf:system/vendor/etc/msm_irqbalance.conf \
    vendor/doro/hero/proprietary/bin/thermal-engine:system/bin/thermal-engine \
    vendor/doro/hero/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/doro/hero/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/doro/hero/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so \
    vendor/doro/hero/proprietary/bin/psensorCal:system/bin/psensorCal \
    vendor/doro/hero/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg \
    vendor/doro/hero/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    vendor/doro/hero/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so \
    vendor/doro/hero/proprietary/bin/perfd:system/bin/perfd \
    vendor/doro/hero/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/doro/hero/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/doro/hero/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/doro/hero/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/doro/hero/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/doro/hero/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/doro/hero/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/doro/hero/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/doro/hero/proprietary/bin/radish:system/bin/radish \
    vendor/doro/hero/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/doro/hero/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/doro/hero/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/doro/hero/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/doro/hero/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/doro/hero/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/doro/hero/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/doro/hero/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/doro/hero/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/doro/hero/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/doro/hero/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/doro/hero/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/doro/hero/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/doro/hero/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/doro/hero/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    vendor/doro/hero/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    vendor/doro/hero/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    vendor/doro/hero/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
    vendor/doro/hero/proprietary/vendor/etc/RIDL/qdss.cfg:system/vendor/etc/RIDL/qdss.cfg \
    vendor/doro/hero/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/doro/hero/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    vendor/doro/hero/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/doro/hero/proprietary/bin/cnd:system/bin/cnd \
    vendor/doro/hero/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/doro/hero/proprietary/bin/location-mq:system/bin/location-mq \
    vendor/doro/hero/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/doro/hero/proprietary/bin/lowi-server:system/bin/lowi-server \
    vendor/doro/hero/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/doro/hero/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/doro/hero/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/doro/hero/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/doro/hero/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/doro/hero/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/doro/hero/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/doro/hero/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/doro/hero/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/doro/hero/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    vendor/doro/hero/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/doro/hero/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/doro/hero/proprietary/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
    vendor/doro/hero/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/doro/hero/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/doro/hero/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
    vendor/doro/hero/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/doro/hero/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/doro/hero/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/doro/hero/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/doro/hero/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/doro/hero/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/doro/hero/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so

PRODUCT_COPY_FILES += \
    vendor/doro/hero/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/doro/hero/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/doro/hero/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/doro/hero/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/doro/hero/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt
