# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/doro/hero/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/doro/hero/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/doro/hero/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/doro/hero/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/doro/hero/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/doro/hero/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/doro/hero/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/doro/hero/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/doro/hero/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/doro/hero/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/doro/hero/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/doro/hero/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/doro/hero/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/doro/hero/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/doro/hero/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/doro/hero/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/doro/hero/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/doro/hero/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/doro/hero/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/doro/hero/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/doro/hero/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/doro/hero/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/doro/hero/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/doro/hero/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/doro/hero/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/doro/hero/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/doro/hero/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/doro/hero/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/doro/hero/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/doro/hero/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_mtp.xml:system/etc/mixer_paths_mtp.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skuh.xml:system/etc/mixer_paths_qrd_skuh.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skuhf.xml:system/etc/mixer_paths_qrd_skuhf.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_qrd_skui.xml:system/etc/mixer_paths_qrd_skui.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_skuk.xml:system/etc/mixer_paths_skuk.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_wcd9306.xml:system/etc/mixer_paths_wcd9306.xml \
    vendor/doro/hero/proprietary/etc/mixer_paths_wcd9330.xml:system/etc/mixer_paths_wcd9330.xml \
    vendor/doro/hero/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/doro/hero/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/doro/hero/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/doro/hero/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/doro/hero/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/doro/hero/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so
    vendor/doro/hero/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_COPY_FILES += \
    vendor/doro/hero/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/doro/hero/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/doro/hero/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/doro/hero/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/doro/hero/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/doro/hero/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    vendor/doro/hero/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03
    vendor/doro/hero/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt
